# Generated by Django 4.0.2 on 2022-08-04 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('body', models.CharField(default='Some Text', max_length=1000)),
                ('date_acquired', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('number_of_pages', models.IntegerField()),
            ],
        ),
    ]
